CREATE SCHEMA ESQUEMA_SERVICIO1;
USE ESQUEMA_SERVICIO1;

CREATE TABLE DUEÑO_MASCOTA1
(
ID_DUEÑO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(60) NOT NULL,
APELLIDO VARCHAR(60) NOT NULL,
TIPO_DOC VARCHAR(20) NOT NULL,
NUMERO_DOCUMENTO VARCHAR(30) NOT NULL,
EMAIL VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(60) NOT NULL
);

CREATE TABLE MASCOTA1 
(
ID_MASCOTA INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_MASCOTA VARCHAR(60) NOT NULL,
ENFERMEDAD VARCHAR (5) NOT NULL,
VECES_ATENDIDO VARCHAR(10) NOT NULL 

);



CREATE TABLE ATENCION1
(
ID_ATENCION INT PRIMARY KEY AUTO_INCREMENT,
TIPO_ATENCION VARCHAR (100) NOT NULL,
NUMERO_DE_ATENCIONES VARCHAR (2) NOT NULL
);

CREATE TABLE PRODUCTOS1 (
ID_PRODUCTO INT PRIMARY KEY AUTO_INCREMENT,
TIPO_DE_PRODUCTO VARCHAR (60) NOT NULL,
VALOR_DE_PRODUCTO VARCHAR (60) NOT NULL
);

CREATE TABLE USUARIOS1
(
ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
NOMBRE_USUARIO VARCHAR(60) NOT NULL,
PASSWORD VARCHAR(280) NOT NULL,
EMAIL_USUARIO VARCHAR(60) NOT NULL,
TELEFONO VARCHAR(60) NOT NULL,
ESTADO VARCHAR(50) NOT NULL
);


CREATE TABLE MEDIOS_DE_PAGO1
(
ID_PAGO INT PRIMARY KEY auto_increment,
MEDIO_DE_PAGO VARCHAR(60) NOT NULL
);

CREATE TABLE ADMINISTRACIONES1
(
ID_ADMINISTRACION INT PRIMARY KEY auto_increment,
NOMBRE VARCHAR(60) NOT NULL,
MAIL VARCHAR(60) NULL,
TELEFONO VARCHAR(60) NULL
);






